export const ERROR_MESSAGE = {
  EMPTY_FULL_NAME: 'Please input Full Name.',
  EMPTY_EMAIL_ADDRESS: 'Please input Email Address.',
  EMPTY_PASSWORD: 'Please input Password',
  EMPTY_CURRENT_PASSWORD: 'Please input Current Password',
  EMPTY_NEW_PASSWORD: 'Please input New Password',
  EMPTY_CONFIRM_PASSWORD: 'Please input Confirm Password',
  MISMATCH_PASSWORD: 'New Password and Confirm Password don\'t match.',
  EMPTY_END_DATE: 'Please select end date.',
  UPDATE_SEARCH_CONDITION: 'There is no filter result. Please update filter option.',

  REGISTER_FAIL: 'Failed to register user.\nPlease try again.',
  LOGIN_FAIL: 'Failed to login user.\nPlease try again.',
  FORGOT_PASSWORD_FAIL: 'Failed to send the email for forgot password.',
  CHANGE_PASSWORD_FAIL: 'Failed to send change password.',
  RESET_PASSWORD_FAIL: 'Failed to send reset password.',
  GET_EXPERIENCE_DETAIL_FAIL: 'Experience can\'t be found.',
  GET_HOST_DETAIL_FAIL: 'Host can\'t be found.',
  EMPTY_GUEST_COUNT: 'Please select guest count.',
  UPDATE_USER_PROFILE_FAIL: 'Failed to update profile.',

  NEED_LOGIN_FUNCTION: 'You need to log in to use this function.',
  ENABLE_BOOK_OWN_EXPERIENCE: 'You cannot book your own experience.',
  
  WRONG_CARD_NUMBER: 'The card number is invalid. Check the card details or use a different card.',
  WRONG_CARD_EXPIRATION: 'The card expiration is invalid. Check the card details or use a different card.',
  WRONG_ZIP_CODE: 'The card’s ZIP code is incorrect. Check the card’s ZIP code or use a different card.',
  PASSED_CARD_EXPIRATION: 'The card has expired. Check the expiration date or use a different card.',
  EMPTY_CARD_NUMBER: 'Please input Card Number',
  EMPTY_CARD_EXPIRATION: 'Please input Card Expiration',
  EMPTY_CVC: 'Please input CVC',
  ADD_PAYMENT_METHOD_FAIL: 'Failed to add payment method.',
  UNSELECT_CARD: 'Please select payment method.',
  HOST_HAVE_NO_BANK: 'Host didn’t add any withdrawal methods.',

};
